### ISSUE TITLE
required

### ISSUE THREAD

**Issue by dcs-codes** [Srivatsajbhat/CS3_CP042_TextEditor#1]
Add mind map and functional requirement and flow chart for the application

**Comment by Srivatsajbhat** [comment]
![Screenshot 2023-08-13 111004](https://github.com/Srivatsajbhat/CS3_CP042_TextEditor/assets/94160935/b6743750-9f77-4652-88a0-cd510e6bf368)
Mind map added

**Comment by Srivatsajbhat** [comment]
![Flow Chart](https://github.com/Srivatsajbhat/CS3_CP042_TextEditor/assets/94160935/d81b0bde-7ff1-47f8-a619-9da804e375c2)
flow chart added
